"""Email delivery using Gmail SMTP."""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from daily_news.config import settings
from daily_news.models import NewsDigest

logger = logging.getLogger(__name__)


class EmailDelivery:
    """Send news digest via Gmail SMTP."""

    SMTP_SERVER = "smtp.gmail.com"
    SMTP_PORT = 587

    def __init__(self):
        if not settings.gmail_address or not settings.gmail_app_password:
            raise ValueError("Gmail credentials are required for email delivery")
        self.sender = settings.gmail_address
        self.password = settings.gmail_app_password
        self.recipients = settings.email_recipient_list

    def send_digest(self, digest: NewsDigest) -> bool:
        """Send the news digest via email.

        Args:
            digest: NewsDigest to send

        Returns:
            True if sent successfully
        """
        if not self.recipients:
            logger.warning("No email recipients configured")
            return False

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"World News Digest - {digest.date.strftime('%B %d, %Y')}"
        msg["From"] = self.sender
        msg["To"] = ", ".join(self.recipients)

        # Create both plain text and HTML versions
        text_content = self._render_text_digest(digest)
        html_content = self._render_html_digest(digest)

        msg.attach(MIMEText(text_content, "plain"))
        msg.attach(MIMEText(html_content, "html"))

        try:
            with smtplib.SMTP(self.SMTP_SERVER, self.SMTP_PORT) as server:
                server.starttls()
                server.login(self.sender, self.password)
                server.send_message(msg)

            logger.info(f"Digest sent to {len(self.recipients)} recipients")
            return True

        except smtplib.SMTPAuthenticationError as e:
            logger.error(f"SMTP authentication failed: {e}")
            return False
        except smtplib.SMTPException as e:
            logger.error(f"SMTP error: {e}")
            return False
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False

    def _render_text_digest(self, digest: NewsDigest) -> str:
        """Render digest as plain text."""
        lines = [
            f"WORLD NEWS DIGEST - {digest.date.strftime('%B %d, %Y')}",
            "=" * 50,
            f"Top {len(digest.top_stories)} Stories",
            "",
        ]

        for i, article in enumerate(digest.top_stories, 1):
            lines.extend(
                [
                    f"{i}. {article.title}",
                    f"   Source: {article.source_name} ({article.source_region.value})",
                    f"   Score: {article.significance_score:.0f}/100",
                    f"   {article.url}",
                    "",
                ]
            )

        lines.extend(
            [
                "-" * 50,
                "Collection Stats:",
                f"  Sources: {digest.collection_stats.sources_succeeded}/{digest.collection_stats.sources_attempted}",
                f"  Articles collected: {digest.collection_stats.articles_collected}",
                f"  After dedup: {digest.collection_stats.articles_after_dedup}",
                "",
                "Generated by Daily News Aggregator",
            ]
        )

        return "\n".join(lines)

    def _render_html_digest(self, digest: NewsDigest) -> str:
        """Render digest as HTML email."""
        stories_html = ""
        for i, article in enumerate(digest.top_stories, 1):
            region_badge = self._get_region_badge(article.source_region.value)
            category_badge = self._get_category_badge(article.source_category.value)

            stories_html += f"""
            <tr>
                <td style="padding: 15px 0; border-bottom: 1px solid #eee;">
                    <div style="font-size: 11px; color: #666; margin-bottom: 5px;">
                        {region_badge} {category_badge}
                        <span style="float: right;">Score: {article.significance_score:.0f}/100</span>
                    </div>
                    <a href="{article.url}" style="font-size: 16px; color: #1a0dab; text-decoration: none; font-weight: 500;">
                        {i}. {article.title}
                    </a>
                    <div style="font-size: 13px; color: #545454; margin-top: 5px;">
                        {article.description[:200]}{"..." if len(article.description) > 200 else ""}
                    </div>
                    <div style="font-size: 12px; color: #006621; margin-top: 5px;">
                        {article.source_name}
                    </div>
                </td>
            </tr>
            """

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0;">
                <h1 style="margin: 0; font-size: 24px;">World News Digest</h1>
                <p style="margin: 5px 0 0 0; opacity: 0.9;">{digest.date.strftime("%B %d, %Y")}</p>
            </div>

            <div style="background: #f8f9fa; padding: 15px; border-left: 1px solid #ddd; border-right: 1px solid #ddd;">
                <strong>{len(digest.top_stories)} Top Stories</strong> |
                Sources: {digest.collection_stats.sources_succeeded}/{digest.collection_stats.sources_attempted} |
                Articles: {digest.collection_stats.articles_after_dedup}
            </div>

            <table style="width: 100%; border-collapse: collapse; background: white; border: 1px solid #ddd;">
                {stories_html}
            </table>

            <div style="background: #f8f9fa; padding: 15px; text-align: center; font-size: 12px; color: #666; border: 1px solid #ddd; border-top: none; border-radius: 0 0 8px 8px;">
                Generated by Daily News Aggregator<br>
                <a href="https://github.com" style="color: #666;">Unsubscribe</a>
            </div>
        </body>
        </html>
        """

    def _get_region_badge(self, region: str) -> str:
        """Get HTML badge for region."""
        colors = {
            "americas_us": "#3498db",
            "americas_latam": "#9b59b6",
            "europe": "#2ecc71",
            "asia_pacific": "#e74c3c",
            "middle_east": "#f39c12",
            "africa": "#1abc9c",
            "local_ny": "#e67e22",
            "global": "#95a5a6",
        }
        color = colors.get(region, "#95a5a6")
        label = region.replace("_", " ").title()
        return f'<span style="background: {color}; color: white; padding: 2px 6px; border-radius: 3px; font-size: 10px;">{label}</span>'

    def _get_category_badge(self, category: str) -> str:
        """Get HTML badge for category."""
        colors = {
            "general": "#7f8c8d",
            "politics": "#c0392b",
            "economy": "#27ae60",
            "technology": "#8e44ad",
            "local": "#d35400",
        }
        color = colors.get(category, "#7f8c8d")
        return f'<span style="background: {color}; color: white; padding: 2px 6px; border-radius: 3px; font-size: 10px;">{category.title()}</span>'
