"""Email delivery using Gmail SMTP."""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from urllib.parse import quote

from daily_news.config import settings
from daily_news.models import NewsDigest

logger = logging.getLogger(__name__)


class EmailDelivery:
    """Send news digest via Gmail SMTP."""

    SMTP_SERVER = "smtp.gmail.com"
    SMTP_PORT = 587

    def __init__(self):
        if not settings.gmail_address or not settings.gmail_app_password:
            raise ValueError("Gmail credentials are required for email delivery")
        self.sender = settings.gmail_address
        self.password = settings.gmail_app_password
        self.recipients = settings.email_recipient_list

    def send_digest(self, digest: NewsDigest) -> bool:
        """Send the news digest via email.

        Args:
            digest: NewsDigest to send

        Returns:
            True if sent successfully
        """
        if not self.recipients:
            logger.warning("No email recipients configured")
            return False

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"World News Digest - {digest.date.strftime('%B %d, %Y')}"
        msg["From"] = self.sender
        msg["To"] = ", ".join(self.recipients)

        # Create both plain text and HTML versions
        text_content = self._render_text_digest(digest)
        html_content = self._render_html_digest(digest)

        msg.attach(MIMEText(text_content, "plain"))
        msg.attach(MIMEText(html_content, "html"))

        try:
            with smtplib.SMTP(self.SMTP_SERVER, self.SMTP_PORT) as server:
                server.starttls()
                server.login(self.sender, self.password)
                server.send_message(msg)

            logger.info(f"Digest sent to {len(self.recipients)} recipients")
            return True

        except smtplib.SMTPAuthenticationError as e:
            logger.error(f"SMTP authentication failed: {e}")
            return False
        except smtplib.SMTPException as e:
            logger.error(f"SMTP error: {e}")
            return False
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False

    def _render_text_digest(self, digest: NewsDigest) -> str:
        """Render digest as plain text."""
        lines = [
            f"WORLD NEWS DIGEST - {digest.date.strftime('%B %d, %Y')}",
            "=" * 50,
            f"Top {len(digest.top_stories)} Stories",
            "",
        ]

        for i, article in enumerate(digest.top_stories, 1):
            lines.extend(
                [
                    f"{i}. {article.title}",
                    f"   Source: {article.source_name} ({article.source_region.value})",
                    f"   Score: {article.significance_score:.0f}/100",
                    f"   {article.url}",
                    "",
                ]
            )

        lines.extend(
            [
                "-" * 50,
                "Collection Stats:",
                f"  Sources: {digest.collection_stats.sources_succeeded}/{digest.collection_stats.sources_attempted}",
                f"  Articles collected: {digest.collection_stats.articles_collected}",
                f"  After dedup: {digest.collection_stats.articles_after_dedup}",
                "",
                "Generated by Daily News Aggregator",
            ]
        )

        return "\n".join(lines)

    def _render_html_digest(self, digest: NewsDigest) -> str:
        """Render digest as HTML email."""
        stories_html = ""
        for i, article in enumerate(digest.top_stories, 1):
            region_badge = self._get_region_badge(article.source_region.value)
            # Use reader-friendly URL if available
            reader_url = self._get_reader_url(str(article.url))
            description = article.description[:250] if article.description else ""

            stories_html += f"""
            <tr>
                <td style="padding: 20px 24px; border-bottom: 1px solid #e8e8e8;">
                    <table style="width: 100%;" cellpadding="0" cellspacing="0">
                        <tr>
                            <td style="vertical-align: top; width: 36px;">
                                <div style="background: #f0f0f0; color: #666; width: 28px; height: 28px; border-radius: 50%; text-align: center; line-height: 28px; font-size: 13px; font-weight: 600;">{i}</div>
                            </td>
                            <td style="vertical-align: top; padding-left: 12px;">
                                <div style="margin-bottom: 8px;">
                                    {region_badge}
                                    <span style="color: #888; font-size: 12px; margin-left: 8px;">{article.source_name}</span>
                                </div>
                                <a href="{reader_url}" style="font-size: 17px; color: #1a1a1a; text-decoration: none; font-weight: 600; line-height: 1.3; display: block;">
                                    {article.title}
                                </a>
                                <p style="font-size: 14px; color: #555; margin: 10px 0 0 0; line-height: 1.5;">
                                    {description}{"..." if len(article.description or "") > 250 else ""}
                                </p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            """

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="margin: 0; padding: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
            <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f5f5f5; padding: 20px 0;">
                <tr>
                    <td align="center">
                        <table width="600" cellpadding="0" cellspacing="0" style="max-width: 600px; width: 100%;">
                            <!-- Header -->
                            <tr>
                                <td style="background: linear-gradient(135deg, #0f0f23 0%, #1a1a3e 100%); padding: 32px 24px; border-radius: 12px 12px 0 0;">
                                    <h1 style="margin: 0; font-size: 28px; font-weight: 700; color: white; letter-spacing: -0.5px;">World News Digest</h1>
                                    <p style="margin: 8px 0 0 0; font-size: 15px; color: rgba(255,255,255,0.8);">{digest.date.strftime("%A, %B %d, %Y")}</p>
                                </td>
                            </tr>

                            <!-- Stats Bar -->
                            <tr>
                                <td style="background: #fafafa; padding: 16px 24px; border-left: 1px solid #e8e8e8; border-right: 1px solid #e8e8e8;">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td style="font-size: 14px; color: #444;">
                                                <strong style="color: #1a1a1a;">{len(digest.top_stories)} Top Stories</strong>
                                                <span style="color: #999; margin: 0 8px;">•</span>
                                                <span style="color: #666;">Sources: {digest.collection_stats.sources_succeeded}/{digest.collection_stats.sources_attempted}</span>
                                                <span style="color: #999; margin: 0 8px;">•</span>
                                                <span style="color: #666;">Articles: {digest.collection_stats.articles_after_dedup}</span>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>

                            <!-- Stories -->
                            <tr>
                                <td style="background: white; border-left: 1px solid #e8e8e8; border-right: 1px solid #e8e8e8;">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        {stories_html}
                                    </table>
                                </td>
                            </tr>

                            <!-- Footer -->
                            <tr>
                                <td style="background: #fafafa; padding: 20px 24px; text-align: center; border: 1px solid #e8e8e8; border-top: none; border-radius: 0 0 12px 12px;">
                                    <p style="margin: 0; font-size: 13px; color: #888;">
                                        Generated by Daily News Aggregator
                                    </p>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </body>
        </html>
        """

    def _get_reader_url(self, url: str) -> str:
        """Convert URL to reader-friendly version that bypasses paywalls.

        Uses archive.ph for paywalled sites (more reliable than archive.today).
        """
        paywall_domains = [
            "nytimes.com",
            "washingtonpost.com",
            "wsj.com",
            "ft.com",
            "economist.com",
            "bloomberg.com",
            "theatlantic.com",
            "newyorker.com",
            "wired.com",
            "thetimes.co.uk",
            "telegraph.co.uk",
            "haaretz.com",
            "barrons.com",
            "foreignpolicy.com",
        ]

        for domain in paywall_domains:
            if domain in url:
                # Use archive.ph with URL-encoded target (more reliable)
                encoded_url = quote(url, safe="")
                return f"https://archive.ph/newest/{encoded_url}"

        return url

    def _get_region_badge(self, region: str) -> str:
        """Get HTML badge for region."""
        colors = {
            "americas_us": "#2563eb",
            "americas_latam": "#7c3aed",
            "europe": "#059669",
            "asia_pacific": "#dc2626",
            "middle_east": "#d97706",
            "africa": "#0891b2",
            "local_ny": "#ea580c",
            "global": "#6b7280",
        }
        labels = {
            "americas_us": "US",
            "americas_latam": "Latin America",
            "europe": "Europe",
            "asia_pacific": "Asia Pacific",
            "middle_east": "Middle East",
            "africa": "Africa",
            "local_ny": "NYC",
            "global": "Global",
        }
        color = colors.get(region, "#6b7280")
        label = labels.get(region, region.replace("_", " ").title())
        return f'<span style="background: {color}; color: white; padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: 500; letter-spacing: 0.3px;">{label}</span>'
